// Paires de mots classées par catégorie. { a: mot citoyens, b: mot imposteur }
module.exports = {
  nourriture: {
    emoji: "🍕", label: "Nourriture & boissons",
    pairs: [
      ["Pizza", "Burger"],
      ["Banane", "Pomme"],
      ["Thé", "Café"],
      ["Chocolat", "Vanille"],
      ["Crêpe", "Gaufre"],
      ["Ketchup", "Mayonnaise"],
      ["Pâtes", "Riz"],
      ["Pain", "Brioche"],
      ["Eau", "Soda"],
      ["Vin", "Bière"],
      ["Fraise", "Framboise"],
      ["Orange", "Clémentine"],
      ["Sel", "Poivre"],
      ["Sucre", "Farine"],
      ["Sushi", "Maki"],
      ["Salade", "Épinard"],
      ["Yaourt", "Fromage blanc"],
      ["Poulet", "Dinde"],
      ["Saumon", "Thon"],
      ["Chips", "Pop-corn"],
      ["Miel", "Confiture"],
      ["Lait", "Crème"],
      ["Oignon", "Ail"],
      ["Citron", "Pamplemousse"],
      ["Baguette", "Croissant"],
      ["Tacos", "Kebab"],
      ["Soupe", "Bouillon"],
      ["Cookie", "Brownie"],
      ["Melon", "Pastèque"],
      ["Champagne", "Cidre"],
      ["Oeuf", "Omelette"]
    ]
  },
  animaux: {
    emoji: "🐾", label: "Animaux",
    pairs: [
      ["Lion", "Tigre"],
      ["Chien", "Loup"],
      ["Chat", "Renard"],
      ["Cheval", "Âne"],
      ["Aigle", "Faucon"],
      ["Requin", "Dauphin"],
      ["Abeille", "Guêpe"],
      ["Mouche", "Moustique"],
      ["Grenouille", "Crapaud"],
      ["Poule", "Canard"],
      ["Vache", "Taureau"],
      ["Mouton", "Chèvre"],
      ["Souris", "Rat"],
      ["Lapin", "Lièvre"],
      ["Serpent", "Lézard"],
      ["Papillon", "Libellule"],
      ["Ours", "Panda"],
      ["Pingouin", "Manchot"],
      ["Gorille", "Chimpanzé"],
      ["Crocodile", "Alligator"],
      ["Chameau", "Dromadaire"],
      ["Fourmi", "Araignée"],
      ["Hibou", "Chouette"]
    ]
  },
  maison: {
    emoji: "🏠", label: "Objets & maison",
    pairs: [
      ["Stylo", "Crayon"],
      ["Chaise", "Tabouret"],
      ["Table", "Bureau"],
      ["Lit", "Canapé"],
      ["Fourchette", "Cuillère"],
      ["Assiette", "Bol"],
      ["Verre", "Tasse"],
      ["Lampe", "Ampoule"],
      ["Porte", "Fenêtre"],
      ["Clé", "Serrure"],
      ["Tapis", "Moquette"],
      ["Miroir", "Vitre"],
      ["Savon", "Shampoing"],
      ["Brosse à dents", "Dentifrice"],
      ["Serviette", "Gant"],
      ["Oreiller", "Coussin"],
      ["Couette", "Couverture"],
      ["Livre", "Magazine"],
      ["Cahier", "Feuille"],
      ["Ciseaux", "Couteau"],
      ["Marteau", "Tournevis"],
      ["Scie", "Hache"],
      ["Valise", "Sac à dos"],
      ["Parapluie", "Imperméable"],
      ["Montre", "Horloge"]
    ]
  },
  vetements: {
    emoji: "👕", label: "Vêtements",
    pairs: [
      ["Bague", "Bracelet"],
      ["Collier", "Écharpe"],
      ["Pantalon", "Short"],
      ["T-shirt", "Chemise"],
      ["Pull", "Sweat"],
      ["Manteau", "Veste"],
      ["Chaussette", "Chaussure"],
      ["Botte", "Basket"],
      ["Chapeau", "Casquette"],
      ["Gants", "Moufles"],
      ["Ceinture", "Bretelles"],
      ["Pyjama", "Robe de chambre"],
      ["Maillot de bain", "Sous-vêtement"],
      ["Lunettes", "Lentilles"]
    ]
  },
  lieux: {
    emoji: "🚗", label: "Transports & lieux",
    pairs: [
      ["Avion", "Hélicoptère"],
      ["Voiture", "Camion"],
      ["Océan", "Lac"],
      ["Train", "Métro"],
      ["Bus", "Tramway"],
      ["Vélo", "Moto"],
      ["Bateau", "Paquebot"],
      ["École", "Collège"],
      ["Lycée", "Université"],
      ["Cinéma", "Théâtre"],
      ["Piscine", "Plage"],
      ["Montagne", "Colline"],
      ["Forêt", "Jungle"],
      ["Rivière", "Fleuve"],
      ["Ville", "Village"],
      ["Maison", "Appartement"],
      ["Chambre", "Salon"],
      ["Cuisine", "Salle de bain"],
      ["Pharmacie", "Hôpital"],
      ["Boulangerie", "Pâtisserie"],
      ["Restaurant", "Cantine"],
      ["Parc", "Jardin"],
      ["Pont", "Tunnel"],
      ["Ascenseur", "Escalier"]
    ]
  },
  loisirs: {
    emoji: "⚽", label: "Sports, musique & jeux",
    pairs: [
      ["Piano", "Guitare"],
      ["Tennis", "Ping-Pong"],
      ["Ski", "Snowboard"],
      ["Football", "Rugby"],
      ["Basket", "Handball"],
      ["Natation", "Plongée"],
      ["Danse", "Gymnastique"],
      ["Peinture", "Dessin"],
      ["Cinéma", "Netflix"],
      ["Jeux vidéo", "Jeux de société"],
      ["Violon", "Violoncelle"],
      ["Batterie", "Tambour"],
      ["Flûte", "Trompette"],
      ["Judo", "Karaté"],
      ["Boxe", "Lutte"],
      ["Surf", "Skate"],
      ["Échecs", "Dames"],
      ["Carte", "Dé"]
    ]
  },
  tech: {
    emoji: "📱", label: "Tech & marques",
    pairs: [
      ["Téléphone", "Tablette"],
      ["Ordinateur", "Télévision"],
      ["Clavier", "Souris"],
      ["Facebook", "Instagram"],
      ["Twitter", "TikTok"],
      ["Email", "SMS"],
      ["Wifi", "4G"],
      ["Chargeur", "Batterie"],
      ["Photo", "Vidéo"],
      ["Casque", "Écouteurs"],
      ["Google", "Wikipedia"],
      ["Apple", "Samsung"],
      ["PlayStation", "Xbox"]
    ]
  },
  nature: {
    emoji: "🌦️", label: "Nature & météo",
    pairs: [
      ["Sable", "Gravier"],
      ["Soleil", "Lune"],
      ["Pluie", "Neige"],
      ["Nuage", "Brouillard"],
      ["Vent", "Tempête"],
      ["Feu", "Fumée"],
      ["Glace", "Eau"],
      ["Terre", "Sable"],
      ["Pierre", "Caillou"],
      ["Arbre", "Buisson"],
      ["Fleur", "Rose"],
      ["Herbe", "Feuille"],
      ["Étoile", "Planète"],
      ["Jour", "Nuit"],
      ["Été", "Hiver"],
      ["Printemps", "Automne"]
    ]
  },
  gens: {
    emoji: "🧑‍⚕️", label: "Corps & métiers",
    pairs: [
      ["Main", "Pied"],
      ["Doigt", "Orteil"],
      ["Oeil", "Oreille"],
      ["Nez", "Bouche"],
      ["Dent", "Langue"],
      ["Cheveux", "Barbe"],
      ["Bras", "Jambe"],
      ["Coude", "Genou"],
      ["Coeur", "Poumon"],
      ["Sang", "Veine"],
      ["Docteur", "Infirmier"],
      ["Policier", "Pompier"],
      ["Professeur", "Élève"],
      ["Boulanger", "Cuisinier"],
      ["Chanteur", "Acteur"],
      ["Juge", "Avocat"],
      ["Soldat", "Général"],
      ["Pilote", "Chauffeur"]
    ]
  },
  concepts: {
    emoji: "💭", label: "Idées & verbes",
    pairs: [
      ["Amour", "Amitié"],
      ["Joie", "Bonheur"],
      ["Peur", "Surprise"],
      ["Colère", "Haine"],
      ["Rêve", "Cauchemar"],
      ["Mensonge", "Vérité"],
      ["Question", "Réponse"],
      ["Début", "Fin"],
      ["Guerre", "Paix"],
      ["Travail", "Vacances"],
      ["Mariage", "Divorce"],
      ["Naître", "Mourir"],
      ["Gagner", "Perdre"],
      ["Donner", "Recevoir"],
      ["Acheter", "Vendre"],
      ["Parler", "Crier"],
      ["Marcher", "Courir"]
    ]
  },
};
